version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_user_springboot
    environment:
      MYSQL_DATABASE: db_user_springboot
      MYSQL_USER: authentication_user
      MYSQL_PASSWORD: virgo1984
      MYSQL_ROOT_PASSWORD: virgo1984
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-userapp:latest
    container_name: backend-userapp
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/db_user_springboot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: authentication_user
      SPRING_DATASOURCE_PASSWORD: virgo1984
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8082
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data:
